<<<<<<< HEAD
server:
  port: 8080

spring:
  application:
    name: ppopihouse

  profiles:
    active: local

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
=======
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
>>>>>>> b9a705a (feat(jwt, security): jwt security 추가)
