server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
      ssl:
        enabled: ${REDIS_SSL}

  datasource:
    hikari:
      maximum-pool-size: 3
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

external:
  validation-api:
    base-url: ${VALIDATION_API_BASE_URL}
  ai-api:
    base-url: ${AI_API_BASE_URL}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000
  refresh-expiration: 1209600000

google:
  places:
    api-key: ${GOOGLE_PLACES_API_KEY}
    base-url: https://places.googleapis.com/v1

kakao:
  local:
    rest-api-key: ${KAKAO_API_KEY}
    base-url: https://dapi.kakao.com